### ISSUE TITLE
Use YAML instead of ini for configuration

### ISSUE THREAD

**Issue by smalleni** [openshift-scale/cerberus#10]
It seems better to use a YAML based configuration file when compared to ini as yaml.load() automatically default empty values to None and we can also implement YAML checking using pyyaml or similar.

@chaitanyaenr Thoughts?

**Comment by chaitanyaenr** [comment]
Good idea @smalleni, we will switch to yaml.

**Comment by chaitanyaenr** [comment]
Fixed by https://github.com/openshift-scale/cerberus/pull/22. Thanks to @mohit-sheth for fixing the issue and thanks @smalleni for the suggestion.
