### ISSUE TITLE
Sweet logo for Cerberus

### ISSUE THREAD

**Issue by jtaleric** [openshift-scale/cerberus#15]
All great projects must have a logo!

**Comment by chaitanyaenr** [comment]
@maryshak1996 we loved the logos you designed for Ripsaw, Scale-CI and Pbench. Will you be able to design one for this project as well please?

A little bit of background as to why we named it Cerberus:
Cerberus is a three headed monster guarding the hell to prevent the people from escaping in greek mythology. This tool is similar in the sense that it guards Kubernetes clouds and prevents failures from escaping by monitoring and generating a signal to let the workloads generators and team know about it.

We found https://dribbble.com/tags/cerberus_logo looking for cerberus logos online, any design which conveys the intention would be great.

**Comment by maryshak1996** [comment]
Hey @chaitanyaenr I'll add this into the UXD visual design queue of graphic design work and I'll let you know when we pull this in, and myself or one of my visual design coworkers will take it on :) I'll keep you posted!

**Comment by chaitanyaenr** [comment]
Thanks @maryshak1996.

**Comment by chaitanyaenr** [comment]
Any update on this @maryshak1996?

**Comment by maryshak1996** [comment]
hey @chaitanyaenr we haven't been able to priortize this yet (with Summit coming soon, there are a lot high priority visual design needs right now). It is in our backlog, as soon as we are ale to get it pulled in I will let you know! Likewise, if you need to consult another designer / design team, just let me know as well :)

**Comment by chaitanyaenr** [comment]
No rush at all, thanks @maryshak1996.

**Comment by chaitanyaenr** [comment]
@maryshak1996 Hi, any update on this?

**Comment by maryshak1996** [comment]
Hey @chaitanyaenr ! I did a bit of work this morning on this --- I came up with two similar iterations on an initial concept that I came up with. This concept is definitely an abstractions of some of the history behind Cerberus
- three distinct bars, as a nod to the three heads of the Cerberus serving a protective purpose
- colors have association with the garb worn in ancient cultures
I would pretty strongly recommend having the logo be an abstraction of the Cerebus, instead of a more direct depiction of the creature -- that could very easily send a confusing message, appear unfriendly, and just in general would likely not read as 'technology'
<img width="1479" alt="Screen Shot 2020-06-23 at 11 11 56 AM" src="https://user-images.githubusercontent.com/19824574/85422379-88c0e280-b543-11ea-8435-6537a6527778.png">
Again, above are just some ideas, but I'm happy to iterate!

**Comment by chaitanyaenr** [comment]
This is awesome @maryshak1996! Agree that the direct depiction of the creature might send a confusing message. I was wondering if we can somehow convey the message in the logo that it guards clouds?

@yashashreesuresh @paigerube14 @mohit-sheth @aakarshg @dry923 @mffiedler @jtaleric @abondvt89 thoughts?

**Comment by mffiedler** [comment]
I really like the "three headed" aspect, it also captures the C-E start of the project name.  Can you do any other color combo mock ups?   I'm thinking red bars on black C or red bars on navy C?  Not menacing, but a nod to the organizational origin of the project.

**Comment by maryshak1996** [comment]
hey guys, thanks for the feedback! @chaitanyaenr I'll have to think a bit on a way to incorporate 'cloud' into the design -- I'd adding a cloud behind the bars might become a little busy, so I'll have to get creative with it :)

as for another color variant, here is an orangey/red with a charcoal version. it needs to be fairly different than the red hat brand, as it is not a red hat PRODUCT.
<img width="1470" alt="Screen Shot 2020-06-26 at 3 17 04 PM" src="https://user-images.githubusercontent.com/19824574/85893226-7a332f00-b7c0-11ea-8403-0332e312dd6d.png">

**Comment by dry923** [comment]
@maryshak1996 The orange/charcoal coloring looks amazing! Thanks! :-D

**Comment by chaitanyaenr** [comment]
@maryshak1996 any update?

**Comment by maryshak1996** [comment]
hey @chaitanyaenr sorry for the *extreme* delay -- I did some updates to incorporate a cloud sort of being shielded by the logo. thoughts here?
<img width="611" alt="Screen Shot 2020-09-14 at 4 40 15 PM" src="https://user-images.githubusercontent.com/19824574/93135948-217d7f00-f6a9-11ea-97c2-76a0d59b74bf.png">

**Comment by chaitanyaenr** [comment]
@maryshak1996 This is amazing, wondering if we can make OpenShift and Kubernetes logos part of the cloud to convey that it monitors OpenShift and Kubernetes clusters if possible? Not sure if it's okay to do it :-)

**Comment by maryshak1996** [comment]
@chaitanyaenr I would suggest against it because the logo could start to look a bit too busy, and I think that it would be a bit iffy to incorporate those other things, from a brand standpoint.

**Comment by chaitanyaenr** [comment]
@maryshak1996 Makes sense.

@paigerube14 @mohit-sheth @jtaleric @mffiedler @dry923 @rsevilla87 @abondvt89 Thoughts on the new logo design?

**Comment by paigerube14** [comment]
Love it!!! Really like the cloud and black and red color scheme!

**Comment by mffiedler** [comment]
+1 from me.   Very nice, @maryshak1996

**Comment by maryshak1996** [comment]
Great!! If people are on board with this, I'll export all the common file types to wrap this up :) @chaitanyaenr do I have a go-ahead from you?

**Comment by mohit-sheth** [comment]
+1, nice work @maryshak1996

**Comment by rsevilla87** [comment]
Really nice @maryshak1996 !!

**Comment by jtaleric** [comment]
This is AWESOME! Thank you @maryshak1996 !!

**Comment by chaitanyaenr** [comment]
> Great!! If people are on board with this, I'll export all the common file types to wrap this up :) @chaitanyaenr do I have a go-ahead from you?
@maryshak1996 Absolutely.

**Comment by maryshak1996** [comment]
Awesome! I've exported SVG, PDF, PNG, and large PNG of:

- Full color (horizontal alignment, vertical alignment, and logomark only)
- All black (horizontal alignment, vertical alignment, and logomark only)
- All white (horizontal alignment, vertical alignment, and logomark only)

You can find those assets here: https://drive.google.com/drive/folders/1NM400ImsnSUxyAtUKJ7TbMUE6G8wOT3M?usp=sharing

**Comment by chaitanyaenr** [comment]
@maryshak1996 Thank you, appreciate it!
