### ISSUE TITLE
Verify application pods not scheduled on master nodes

### ISSUE THREAD

**Issue by mffiedler** [openshift-scale/cerberus#42]
This might be pushing the scope of what cerberus is intended for, but an easy "health check" would be making sure master nodes are not schedule-able for application workloads.   See https://bugzilla.redhat.com/show_bug.cgi?id=1827996

**Comment by mffiedler** [comment]
I don't think this requires a new option in the config, but it is OpenShift specific - not applicable to generic Kubernetes.   We need to make a decision on having a subset of cerberus be OpenShift specific before implementing this.

**Comment by paigerube14** [comment]
@mffiedler I'm thinking here that I should do an "oc describe node/<nodeName>" on all the master nodes and verify under the taints section has node-role.kubernetes.io/master:NoSchedule each time. Looking at the bugzilla link it looked like the Taints section when they ran into the bug was <none>. 

Is this around what you were thinking? Do you know of an easier way to do that?

**Comment by mffiedler** [comment]
Checking for the taint would be correct.   

Bigger picture, I think we need an option for "verbose health checks" that would enable a selection of smaller, optional, nice to have checks.   There are a lot of details about a cluster that can be checked to vet cluster health, but our current set of checks already take 30+ seconds to run on all openshift-* namespaces.   This is likely an issue for a separate issue, but we might want to tackle that before this.  I will open one and we can discuss there /cc: @yashashreesuresh @chaitanyaenr

**Comment by mffiedler** [comment]
See issue #53

**Comment by paigerube14** [comment]
I have created branch [schedMaster](https://github.com/paigerube14/cerberus/tree/schedMaster) for this issue. I have just done a check for the schedule of the master nodes as an always run check, not set in the config. Based on some conversations here and in the attached issue I know this is not going to be the final functionality of this check. 

I am thinking for this specific check I can do a couple of things:

1. Add a command line argument for allowing checks for openshift specific monitoring

2. Add an optional key value pair to the config for checking openshift specific monitoring, would be set to False by default

3. Add a command line argument specifically to see the schedule status of master nodes 

4. Add an optional key value pair to the config to see the schedule status of master nodes, set to False by default

**Comment by paigerube14** [comment]
@mffiedler Do you think this does not require an additional check in the config?

**Comment by mffiedler** [comment]
I don't see a need for a config check here.   This should be part of the standard monitor/check loop.

**Comment by chaitanyaenr** [comment]
Fixed by https://github.com/openshift-scale/cerberus/pull/57. Thanks @paigerube14.
