### ISSUE TITLE
Monitor clusteroperator status

### ISSUE THREAD

**Issue by mffiedler** [openshift-scale/cerberus#43]
In addition to monitoring nodes and pod health, clusteroperator status is another key indicator of cluster health.   

Suggestion for cerberus enhancement:  add a config option to monitor clusteroperator status and watch for degraded operators.    See:  oc get clusteroperators -o yaml

**Comment by mffiedler** [comment]
/cc: @chaitanyaenr @yashashreesuresh  : Assigning this to @paigerube14 .   Please comment if you have suggestions/preferences on the approach.

**Comment by paigerube14** [comment]
Some thoughts on getting started. Please feel free to comment. 

start_cerberus.py: add an optional "watch_operators" key with possible values of True or False to the yaml file 
if the watch_operators value is true, use the invoke function to "oc get clusteroperators -o yaml" 
I couldn't find any kubernetes client functions for the cluster operators area so I think the invoke is the only way to do this. Please point me to it these functions, if they do exist.

Then loop through the output returned from the invoke function to look at the "degraded" column 
Could add the loop in to the client.py file to log which operators are degraded. 

Do we want to be able to know which iteration the certain operator started to degrade, similar to the monitor_component function?

**Comment by chaitanyaenr** [comment]
@paigerube14 The approach sounds good to me. 

https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/AppsV1Api.md doesn't seem to have a way to get the list of cluster operators I guess, so using the invoke function to run the command is the way to go like you mentioned. 

We can display the failure along with name of the cluster operator in degraded state similar to how the components in namespaces are being monitored. Any logging.info statement gets automatically included in the report file generated in the run directory. This way, we can take a look at what cluster operator was failing at what time/iteration and whether it recovered in the next iterations in addition to perf/scale and chaos test automation/tooling using the no-go signal ( False ) to act on the failure.

**Comment by chaitanyaenr** [comment]
Fixed by https://github.com/openshift-scale/cerberus/pull/46. Thanks @paigerube14.
