### ISSUE TITLE
Cerberus errors out when unable to find namespace

### ISSUE THREAD

**Issue by dry923** [openshift-scale/cerberus#44]
When launching the container and it is unable to find the requested namespaces (openshift-sdn and openshift-ovn-kubernetes) Cerberus Errors out. Should this be an error OR should we just be reporting a failed state but continue to start up Cerberus?

```
2020-04-27 20:23:35,693 [ERROR] Could not find openshift-sdn and openshift-ovn-kubernetes namespaces,         please specify the correct networking namespace in config file
Traceback (most recent call last):
  File "start_cerberus.py", line 223, in <module>
    main(options.cfg)
  File "start_cerberus.py", line 50, in main
    watch_namespaces = [w.replace('openshift-sdn', sdn_namespace) for w in watch_namespaces]
  File "start_cerberus.py", line 50, in <listcomp>
    watch_namespaces = [w.replace('openshift-sdn', sdn_namespace) for w in watch_namespaces]
TypeError: replace() argument 2 must be str, not None
```

**Comment by chaitanyaenr** [comment]
Looks like we ran it on Kubernetes cluster as both the openshift-sdn and openshift-ovn-kubernetes namespaces don't exist? We need to set the namespaces to monitor in the config accordingly as the default ones in the config are specific to OCP. Thinking about this, maybe we should add a note in the readme about changing the config depending on the distribution? Thoughts?

**Comment by chaitanyaenr** [comment]
Think it's better to error out when the namespace is not found for the user to know about it.

**Comment by yashashreesuresh** [comment]
I think if a namespace isn't valid, we could log an error message and continue with the monitoring of next namespace in the watch_namespaces as it could be a typo as well.
