### ISSUE TITLE
Monitor apiserver availability

### ISSUE THREAD

**Issue by mffiedler** [openshift-scale/cerberus#47]
While executing chaos (kraken) scenarios,  measure the amount of time the apiserver is unavailable.  The goal is zero downtime, but that is not the current reality.   While the apiserver is unavailable, cerberus should return a no-go signal and ideally maintain a metric with the amount of time it is unavailable.

This can be tested with calls to https://<api url>:<api_port>/healthz.    For OpenShift this might look like https://api.mffiedler-511.perf-testing.devcluster.openshift.com:6443/healthz

**Comment by paigerube14** [comment]
I added the code for this issue to https://github.com/paigerube14/cerberus/tree/apiServer.  I tried to test it while running upgrades and also running kraken.  I was never able to see the api server url go down; so I was not able to test the code properly for the failure if statements. After talking with Mike, he is not sure if this specific test can just be covered with the ability to run oc commands. 
Will have to see if this test case will be helpful for getting the state of the cluster.

**Comment by paigerube14** [comment]
I was finally able to get the correct error state to test this code. NOTE: I had to set the duration to a very low number to be able to get this to work and I commented out all other checks to try to see a better timing. 

I am printing the whole body of the response (Which definitely can/should be taken out) 

_2020-05-15 15:45:38,705 [INFO] Api server text [+]ping ok
[+]log ok
[+]etcd ok
[+]poststarthook/quota.openshift.io-clusterquotamapping ok
[+]poststarthook/openshift.io-startkubeinformers ok
[+]poststarthook/openshift.io-StartOAuthInformers ok
[+]poststarthook/start-kube-apiserver-admission-initializer ok
[+]poststarthook/generic-apiserver-start-informers ok
[+]poststarthook/priority-and-fairness-config-consumer ok
[+]poststarthook/start-apiextensions-informers ok
[+]poststarthook/start-apiextensions-controllers ok
[+]poststarthook/crd-informer-synced ok
[-]poststarthook/bootstrap-controller failed: reason withheld
[-]poststarthook/rbac/bootstrap-roles failed: reason withheld
[-]poststarthook/scheduling/bootstrap-system-priority-classes failed: reason withheld
[+]poststarthook/apiserver/bootstrap-system-flowcontrol-configuration ok
[+]poststarthook/start-cluster-authentication-info-controller ok
[+]poststarthook/aggregator-reload-proxy-client-cert ok
[+]poststarthook/start-kube-aggregator-informers ok
[+]poststarthook/apiservice-registration-controller ok
[+]poststarthook/apiservice-status-available-controller ok
[+]poststarthook/apiservice-wait-for-first-sync ok
[+]poststarthook/kube-apiserver-autoregistration ok
[+]autoregister-completion ok
[+]poststarthook/apiservice-openapi-controller ok
healthz check failed

2020-05-15 15:45:38,707 [INFO] Api not 200
2020-05-15 15:45:38,707 [INFO] Sleeping for the specified duration: 3


2020-05-15 15:45:45,461 [INFO] Api server text ok
2020-05-15 15:45:45,461 [INFO] Api server was down for 0:00:06.753424_




@mffiedler  Do you feel like this is a good sanity check to have included at all times in cerberus or it will fail to infrequently that it's not worth it?

**Comment by chaitanyaenr** [comment]
Fixed by https://github.com/openshift-scale/cerberus/pull/56. Thanks @paigerube14.
