### ISSUE TITLE
Monitor application/ingress route availability (OpenShift specific monitor)

### ISSUE THREAD

**Issue by mffiedler** [openshift-scale/cerberus#48]
While executing chaos (kraken) scenarios, measure the amount of time the ingress routes to applications are unavailable. The goal is zero downtime, but that is not the current reality. 

While the appications routes are unavailable, cerberus should return a no-go signal and ideally maintain a metric with the amount of time they unavailable.

This should be an optional config item which:
1.  sets up a quickstart application (e.g.  oc new-app -t nodejs-mongodb-example
2.  retrieves the route for the new application
3.  monitors the availability of the route (200 vs other)

**Comment by chaitanyaenr** [comment]
@mffiedler Think this fits more in Kraken where we will have specific scenarios focused on various components. The plan is to add ability in Kraken to run the user provided health checks post scenario injection to decide pass/fail in addition to consuming Cerberus go/no-go signal at the end of the scenario for making sure the cluster and critical components are healthy as a whole. Thoughts?

**Comment by paigerube14** [comment]
I definitely agree that the first two steps should be a kraken scenario. But we would need to add an option to maybe pass in the specific route that we want to verify is available through out the chaos. Or we could check if all routes continue to be available (a more generalized command line option?)

**Comment by chaitanyaenr** [comment]
@paigerube14 so an option in Cerberus to check if the routes are available in the given namespaces?

**Comment by paigerube14** [comment]
Yes. I was trying to think about it for a generic test case and a specific test case. Not sure if it would be as useful for the generic case.

**Comment by mffiedler** [comment]
A Kraken scenario would provide chaos testing for ingress and is definitely of value.   I think we need a simple test of a route as part of the Cerberus monitor loop to act as a canary/sanity test that ingress uptime is as close to 100% as possible during other scenarios which do not focus specifically on ingress.

There's a big push on the engineering time to keep user application availability as close to 100% as possible during upgrades and other cluster changes, including instability.   An alternative to testing availability of a quickstart would be to check availability of built-in routes (console, prometheus, grafana).   Nothing fancy, just reach-ability.

**Comment by chaitanyaenr** [comment]
@paigerube14 @mffiedler Agreed, adding a way to check the reachability of the routes given a namespace in Ceberus makes sense. Let's do it.

**Comment by paigerube14** [comment]
Awesome, sounds good! 

Do you think we should add a new namespace variable to the config file for this or just look at the routes for each of the namespaces in the current watch_namespaces section of the config?

**Comment by chaitanyaenr** [comment]
@paigerube14 Think we can check the routes in each of the namespaces specified under current watch_namespaces section of the config as we might want to monitor the status of the pods/containers in addition to the routes.

**Comment by paigerube14** [comment]
Ok sounds good, I will add checking of all routes that are in the given namespaces defined in watch_namespaces.  In addition, I will check any routes defined by an optional item in the config.  Would you expect to pass the name of the route and I find it from the list of routes in all namespaces or just pass in the url you want to monitor?

**Comment by chaitanyaenr** [comment]
@paigerube14 Maybe add an option in config which when set will watch all the routes in defined namespaces under watch_namespaces option of the config, this way we have a way to watch/not watch routes in the defined namespaces. Also add an option called watch_routes or watch_urls where user can provide a list of urls to monitor. Thoughts?

**Comment by paigerube14** [comment]
I really like that idea! I am thinking about the option "watch_namespace_routes" for watching the routes based on defined namespaces (a True or False) and then watch_url_routes. I could switch the second one to just watch_urls to be more generic. But the urls would be the exact format you want to do a get request on, correct?

**Comment by chaitanyaenr** [comment]
@paigerube14 You are right, the urls need to be in the pingable format.

**Comment by paigerube14** [comment]
@chaitanyaenr Is it safe to assume the authorization should use the bearer token as well as the insecure option (i=-k for curl, verify=false in requests)?

**Comment by chaitanyaenr** [comment]
@paigerube14 We can set verify=false by default and provide a way for the user to pass in the certs if needed like you mentioned. Think we can ignore certs for the first pass.

**Comment by chaitanyaenr** [comment]
Fixed by https://github.com/openshift-scale/cerberus/pull/72. Thanks @paigerube14.
