### ISSUE TITLE
Track Kube/OpenShift object restarts

### ISSUE THREAD

**Issue by chaitanyaenr** [openshift-scale/cerberus#51]
@mffiedler suggested an enhancement for Cerberus to monitor pod restarts. Cerberus will miss a failure if a pod restarts and gets back to running state during the wait time between each iteration. It needs to check if there was restart for each iteration and take it into consideration for setting the go/no-go signal.

One way to implement this would to be keep track of the restart count at the start and stop of each iteration and compare them to know if there was a pod restart during the wait time.

**Comment by chaitanyaenr** [comment]
@yashashreesuresh @mffiedler @jtaleric Thoughts?

**Comment by mffiedler** [comment]
I think this should be communicated as warning/informational data and not necessarily a no-go signal.   This gets into some fuzzy territory that will require us to evaluate initially (e.g. a pod that restarted once vs an apiserver restarting 20 times)
