### ISSUE TITLE
[RFE] New API for capturing number of failures

### ISSUE THREAD

**Issue by jtaleric** [openshift-scale/cerberus#58]
Today we have a single signal, `go/no-go`, however this signal could miss operators/pods flapping. We should provide an additional signal, which accepts a time range. This signal will report the number of failures seen within the time window. 

`/history?lookback=60`

`lookback` should be in minutes, and allow the user to determine how far back in time they want to know if failures happened.

The return of this should be json
```
history : {
  duration: int(),
  failures : {
    count: int(),
    issues : [ list of problems that occurred in the duration ]
  }
} 
```

The history api will provide the user/tool with more data to determine if they should continue on, or stop. 

Thoughts?

**Comment by dry923** [comment]
I like it but I'd be more inclined for a list of failure types each one with a count. That way we can weigh each failure differently (ie etcd crashing versus node offline). For example

```
history : {
  duration: int(),
  failure : [
    {
        count: int(),
        issue : [ the issue that occurred ]
    },
    {
        count: int(),
        issue: [another issue that occurred]
  }
}

**Comment by chaitanyaenr** [comment]
+1 I like the idea as well. Just a minor suggestion on the implementation part, think we should have an field called type like @dry923 mentioned for the user to filter and get the failure count related to a particular component of interest and act accordingly. For example: 

```
history : {
  duration: int(),
  failure : [
    {
        count: int(),
        issue : [ the issue that occurred ]
        type: etcd
    },
    {
        count: int(),
        issue: [the issue that occurred]
        type: apiserver
    }
  ]
} 
```
This way the control plane focused tests can filter on type: apiserver and type: etcd to get the failure count and the list of issues for example.

**Comment by paigerube14** [comment]
I agree that this is a great idea!!! 

Going off of what Ravi commented on, I agree a type should be specified for the certain issues. This might be a little over kill for this report but right now we list the issues together per resource area (cluster operators, pods, nodes). Would it be worth while to try to combine all these areas by the type so we could list all failed operators, pods, nodes etc that deal with the certain type in one list? And maybe adding the iteration in where they failed so we could know when things went down in certain iterations but if they came back and are stable again. We could add a current iteration counter at the top so we know which iteration we currently are in to see if any failures are in the current iteration or if things have become more stable

history : {
  duration: int(),
  iteration_count: int(),
  failure : [
    {
        count: int(),
        issue : [ Iteration 1: node x failed, 
                     Iteration 1: pod x failed
                     Iteration 2: cluster operator openshift-etcd failed...]
        type: etcd
    },
    {
        count: int(),
        issue: [the issue that occurred]
        type: apiserver
    }
  ]
}

**Comment by jtaleric** [comment]
> I agree that this is a great idea!!!
> 
> Going off of what Ravi commented on, I agree a type should be specified for the certain issues. This might be a little over kill for this report but right now we list the issues together per resource area (cluster operators, pods, nodes). Would it be worth while to try to combine all these areas by the type so we could list all failed operators, pods, nodes etc that deal with the certain type in one list? And maybe adding the iteration in where they failed so we could know when things went down in certain iterations but if they came back and are stable again. We could add a current iteration counter at the top so we know which iteration we currently are in to see if any failures are in the current iteration or if things have become more stable
> 
> ```
> history : {
>    duration: int(),
>    iteration_count: int(),
>    failure : [
>      {
>          count: int(),
>          issue : [ Iteration 1: node x failed, 
>                       Iteration 1: pod x failed
>                       Iteration 2: cluster operator openshift-etcd failed...]
>          type: etcd
>      },
>      {
>          count: int(),
>          issue: [the issue that occurred]
>          type: apiserver
>      }
>    ]
>  }
> ```
> 
> Thoughts?

Awesome iterations on the idea folks! Some more thoughts

`type` should be more aligned with where failure came from, ie operator/pod/system/etc.

Possibly introduce `component`, which could be `apiserver` etc... Thoughts? 

I wanted to keep the json simple, that way if all the user/tool cares about is `count(history.failures)` they can get that insight.

**Comment by yashashreesuresh** [comment]
Awesome idea! Adding to Ravi's idea on the implementation part and Joe's idea on introducing `component`, maybe we could add a set of issues for each component which indicate the different types of issues and their respective count. The total_count would be the overall summation.
```
history : {
  duration: int(),
  failure : [
    {
        total_count: int(),
        issues: {
          pod crash/restarts: count,
          operator failures: count
        }
        component: etcd
    },
    {
        total_count: int(),
        issues: {
          issue: count, 
          issue: count
        }
        component: apiserver
    }
  ]
} 
```
